### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ruisebastiao** [steveukx/git-js#120]
Hello,

with the 1.51 update i'm getting the following error:

`TypeError: Cannot read property 'replace' of undefined
    at c:\Users\RSebastiao\Documents\GitHub\node-BSValidation\node_modules\simple-git\src\TagList.js:24:39
    at Array.sort (native)
    at Function.TagList.parse (c:\Users\RSebastiao\Documents\GitHub\node-BSValidation\node_modules\simple-git\src\TagList.js:15:8)
    at c:\Users\RSebastiao\Documents\GitHub\node-BSValidation\node_modules\simple-git\src\git.js:302:57
    at Git.<anonymous> (c:\Users\RSebastiao\Documents\GitHub\node-BSValidation\node_modules\simple-git\src\git.js:713:18)
    at Git.<anonymous> (c:\Users\RSebastiao\Documents\GitHub\node-BSValidation\node_modules\simple-git\src\git.js:1105:21)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:211:5)`

I have the following tags: V1.0, V1.0.1

checking the code:

for (var i = 0, l = Math.max(partsA.length, partsB.length); i < l; i++) {
           var a = parseInt(partsA[i].replace(/^\D+/g, ''), 10) || 0;
           var b = parseInt(partsB[i].replace(/^\D+/g, ''), 10) || 0;
            var diff = a - b;
            if (diff) {
               return diff > 0 ? 1 : -1;
            }
         }

partsA.length =2, partsB.length=3 so partsA[2] is undefined,

i solved the problems by using tabs with same name "length" but i think you should prevent this.

Best Regards,
Rui

**Comment by steveukx** [comment]
Thanks for the detailed issue report - a new test case has been added and the issue resolved, available as 1.52.0 on npm now
