### ISSUE TITLE
git clone, 'Error: spawn git ENOENT'

### ISSUE THREAD

**Issue by koooge** [steveukx/git-js#128]
Hi, is this intented?

I try to `git clone`
```
const repoPath = 'path/to/repo',
          localPath= 'path/to/localDir';
let simpleGit = require('simple-git')(localPath); // NG
// let simpleGit = require('simple-git')(); // this is OK
simpleGit.clone(repoPath, localPath);
```

Error occurred.
```
Error: spawn git ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by steveukx** [comment]
Hi, the `ENOENT` error is thrown when attempting to use the file system on a file that doesn't exist, most commonly this would be because `localPath` (in your example) is a file path that doesn't exist.

I will add a check in for validating file paths shortly, but in the mean time, please can you check that `path/to/localDir` is a directory that is writeable.

**Comment by koooge** [comment]
I see.

but, I want to write as follows.

```
let simpleGit = require('simple-git')(localPath);
if (isExist(localPath)) {
  simpleGit.pull();
} else {
  simpleGit.clone(repoPath, localPath);
}
```

Let me know if you know of any better way?

**Comment by steveukx** [comment]
How about:

```
const exists = require('file-exists');
const git = require('simple-git/promise');

const localRoot = 'some/path/to';
const localRepo = localRoot + '/repo';

let simpleGit = git(localRoot).pull() : git(localRoot).clone(repoPath, localRep);
simpleGit.then((err, result) => {
  // if !err, you should be able to now rely on
  // localRepo always being up to date
});
```

Note - this relies on the use of the new (slightly experimental) promise based version of simple-git.

**Comment by koooge** [comment]
Very thank you.
I go ahead in this way. :smile:
