### ISSUE TITLE
How to use git diff

### ISSUE THREAD

**Issue by no-more** [steveukx/git-js#131]
Hello,

I'm having trouble to use git diff function with a paramter

This one work:
```
simpleGit(pkgDir)
        .add('./*')
        .diffSummary(
        function (err, data) {
            if (err) {
                return bumpPackageCb(err);
            }
}
```

But not this one : 
```
simpleGit(pkgDir)
        .add('./*')
        .diffSummary(["master"],
        function (err, data) {
            if (err) {
                return bumpPackageCb(err);
            }
}
```
here is the error I get:
```
\node_modules\simple-git\src\git.js:724
         then && then(err, !err && require('./DiffSummary').parse(data));
                 ^

TypeError: then is not a function
    at D:\workspaces\PhpStorm\SysCea\syscea-tool-package\node_modules\simple-git\src\git.js:724:18
    at Git.<anonymous> (D:\workspaces\PhpStorm\SysCea\syscea-tool-package\node_modules\simple-git\src\git.js:718:18)
    at Git.<anonymous> (D:\workspaces\PhpStorm\SysCea\syscea-tool-package\node_modules\simple-git\src\git.js:993:21)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

```

Maybe I'm not using the correct parameters ? I want to do a `git diff --stat master`.

Thanks a lot.

**Comment by steveukx** [comment]
Hi, from the stack trace, it looks like you're using an old version of the library. Please can you update to the latest and check whether the error still presents itself.

**Comment by no-more** [comment]
Thanks it's now working, I forgot to check for updates sorry.
