### ISSUE TITLE
1.59.0 breaks ember-cli-deploy

### ISSUE THREAD

**Issue by ip2k** [steveukx/git-js#132]
Hello,

Our work-around for this is to pin ```"simple-git": "1.58.0",``` in package.json. This is the error we see:

```
  +- revision-data
- creating revision data using `git-commit`
- TypeError: path must be a string or Buffer
|
+- didFail
TypeError: path must be a string or Buffer
TypeError: path must be a string or Buffer
  at TypeError (native)
  at Object.fs.statSync (fs.js:981:18)
  at exists (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/simple-git/src/util/exists.js:7:21)
  at module.exports (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/simple-git/src/util/exists.js:28:11)
  at module.exports (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/simple-git/src/index.js:10:21)
  at /var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/ember-cli-deploy-revision-data/lib/scm-data-generators/git.js:15:7
  at initializePromise (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/rsvp/dist/rsvp.js:588:5)
  at PromiseExt.Promise (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/rsvp/dist/rsvp.js:1076:31)
  at new PromiseExt (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/ember-cli/lib/ext/promise.js:32:8)
  at CoreObject.module.exports.CoreObject.extend.generate (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/ember-cli-deploy-revision-data/lib/scm-data-generators/git.js:14:12)
  at Class.DeployPluginBase.extend._getScmData (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/ember-cli-deploy-revision-data/index.js:67:14)
  at Class.DeployPluginBase.extend.prepare (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/ember-cli-deploy-revision-data/index.js:37:23)
  at Object._pipeline.register.fn (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:159:21)
  at Pipeline._notifyPipelinePluginHookExecution (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/ember-cli-deploy/lib/models/pipeline.js:175:19)
  at tryCatch (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/rsvp/dist/rsvp.js:538:12)
  at invokeCallback (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/rsvp/dist/rsvp.js:553:13)
  at /var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/rsvp/dist/rsvp.js:628:16
  at flush (/var/lib/jenkins/jobs/Foggy UI - Canary/workspace/node_modules/rsvp/dist/rsvp.js:2373:5)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
|  |
|  +- slack
|
Pipeline aborted
```

Possibly related: https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/pull/40

**Comment by steveukx** [comment]
Hi, thanks for the full stack trace.

It looks as thought the error is being generated because a non-string is passed to the constructor of `simple-git` in [ember-cli-deploy-revision-data](https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/blob/master/lib/scm-data-generators/git.js#L15). To better diagnose what is causing the error (and to publish a fix), please can you check what value is being used as `_this.path`.

**Comment by ghedamat** [comment]
@steveukx it looks like the error was a bug in our code

https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/pull/45

hopefully this pr will fix it

**Comment by ip2k** [comment]
Thanks for the fast fix @ghedamat and the quick reply @steveukx . We've confirmed that `"ember-cli-deploy-lightning-pack": "^0.6.7"` in our `package.json` fixes this, even without pinning `simple-git`.

Related: https://github.com/ember-cli-deploy/ember-cli-deploy-lightning-pack/pull/29
and: https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/pull/40
