### ISSUE TITLE
spawn git ENOENT again - win7

### ISSUE THREAD

**Issue by romanran** [steveukx/git-js#159]
Hi
I tried using git init and git cwd. I create the directory with mkdirp, it's set to 777. I made start on git.baseDir and the location is all right. I tried installing it globally.

Here is the error
`Error: spawn git ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

I'm on Win7. I've seen the same script running on Win10. Any ideas?

**Comment by steveukx** [comment]
Hi, the most likely cause of an `ENOENT` error when changing the working directory is that the new directory isn't found.

One thing to ensure is that the working directory supplied to `git.cwd` is the absolute path to the new working directory.

While it doesn't necessarily explain why the same script works in Win10 and not on Win7, please update to today's release (1.67.0 on npm) which will now validate that the new path both exists and is a directory and gives better error messages when attempting to switch into a non-directory. 

Please let me know if you have any more problems.

**Comment by Gruntfuggly** [comment]
I have the same issue (with Windows 7). I know the directory exists - I can copy it out of the console log and cd to it in a command shell, but I get Error: spawn git ENOENT when I do 

    git( folder ).raw(...

The path I'm using is absolute and includes the drive letter, e.g.

    var filepath = vscode.Uri.parse( editor.document.uri.path ).fsPath;
    var folder = path.normalize( path.dirname( filepath ) );

**Comment by steveukx** [comment]
Without access to a windows based machine, I've not been able to reproduce this. Please can you paste the full stack trace (if it gives the line number in this library that is the origin of the error), alternatively you can add a break point to [this line](https://github.com/steveukx/git-js/blob/master/src/git.js#L1197) where the child process is spawned which may help diagnose whether the current value of the `this._baseDir` isn't a folder, or is a folder that doesn't have `0777` permissions.

The library should be [catching all fatal exceptions](https://github.com/steveukx/git-js/blob/master/src/git.js#L1208-L1210) in the spawned child process, though it may be worth validating that the `raw` command being run doesn't cause an exception. If it does, the please let me know what kind of exception it is and I'll add handling for that in the library too (or feel free to send a pull request!)
