### ISSUE TITLE
show conflict filenames in error message when git.pull()

### ISSUE THREAD

**Issue by cwtuan** [steveukx/git-js#331]
When I use git cmd to pull from remote branch `git pull origin b1`, the error message shows the conflict detail such as conflict filenames.
```
From gitlab.alibaba-inc.com:g1/p1
 * branch            b1         -> FETCH_HEAD
Auto-merging src/routes/index.js
CONFLICT (content): Merge conflict in src/routes/index.js
Auto-merging src/core/intl.js
Auto-merging README.md
Automatic merge failed; fix conflicts and then commit the result.
```

But When I use `simple-git` to pull from remote branch `git.pull('origin', 'b1')`, the error message isn't clear. Is possible to show the conflict filenames as in git cmd.

```
Error: From http://gitlab.xxxx.com/xxx/my-project2
 * branch            b1         -> FETCH_HEAD

    at /tmp/publish/node_modules/_simple-git@1.107.0@simple-git/promise.js:21:26
    at Git.<anonymous> (/tmp/publish/node_modules/_simple-git@1.107.0@simple-git/src/git.js:1553:13)
    at Function.Git.fail (/tmp/publish/node_modules/_simple-git@1.107.0@simple-git/src/git.js:1478:18)
    at fail (/tmp/publish/node_modules/_simple-git@1.107.0@simple-git/src/git.js:1436:20)
    at /tmp/publish/node_modules/_simple-git@1.107.0@simple-git/src/git.js:1445:16
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by steveukx** [comment]
The detail of the conflict itself is written to stdout instead of stderr so isn't currently captured in the response to be parsed.

Adding custom error handling is currently achieved by either adding an `onError` handler (eg in [checkIsRepo](https://github.com/steveukx/git-js/blob/master/src/git.js#L1311-L1317)) or specifying the option to `concatStdErr` (eg in [fetch](https://github.com/steveukx/git-js/blob/master/src/git.js#L374-L376)) depending on whether the conflict causes a clean or error exit code. If you would like to make a pull request, please do - otherwise I've tagged this as an enhancement to be added when I have more time at the start of next year.

**Comment by cwtuan** [comment]
Looking forward to this feature. Many thanks!
