### ISSUE TITLE
documentation on how to use path unclear

### ISSUE THREAD

**Issue by KarlWestgardh** [steveukx/git-js#409]
I can't seem to get git-js to work apart from running script inside of folder. 
The documentation is not clear whether or not the path should be relative or absolute.. 

Code examples:
(Default path works fine)
- var git = require('simple-git')
- git().pull().tags((err, tags) => console.log("Latest available tag: %s", tags.latest));

(Relative path does not work)
- var git = require('simple-git')
- var path = './my-repo-folder'
- git(path).pull().tags((err, tags) => console.log("Latest available tag: %s", tags.latest));

(Absolute path does not work)
- var git = require('simple-git')
- var path = '/Users/my-user/Documents/my-repo-folder'
- git(path).pull().tags((err, tags) => console.log("Latest available tag: %s", tags.latest));

Error response message:
throw new Error("Cannot use simple-git on a directory that does not exist.");
       ^

Error: Cannot use simple-git on a directory that does not exist.
    at module.exports (/Users/my-user/Documents/node_modules/simple-git/src/index.js:9:14)
    at Object.<anonymous> (/Users/my-user/Documents/git.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

It's a very simple question but I would greatly appreciate any help on this!

**Comment by steveukx** [comment]
Hi, apologies for the delay in replying, have you resolved this yet?

The `simple-git` builder just checks that the supplied path is accessible and is a folder, if you use a relative path it will be relative to the current working directory of the script.

Please try:

```
const {resolve} = require('path');
const {statSync} = require('fs');

const git = require('simple-git');
const path = resolve(__dirname, 'my-repo-folder');

// this shows the path being used and verifies node thinks it is a directory
console.log(path, statSync(path).isDirectory()); 

git(path).pull();

```

**Comment by steveukx** [comment]
Closing due to inactivity
