### ISSUE TITLE
Error responses aren't parsable using promises

### ISSUE THREAD

**Issue by Blasz** [steveukx/git-js#413]
I'm using the merge command and want to detect what the conflicts are.

From the docs:
> Conflicts during the merge result in an error response, the response type whether it was an error or success will be a MergeSummary instance.

The problem is that the `simple-git/promise` wrapper wraps all rejected values with an `Error` which converts these error response data structures to strings so I cannot parse them.

I'd suggest not wrapping these values in an `Error` as the stack traces don't provide much value imo:

e.g.

```
Error: CONFLICTS: packages/foo/bar/package.json:content
    at Git.<anonymous> (/Users/u/dev/atlaskit-mk-2/node_modules/simple-git/promise.js:62:29)
    at Function.Git.fail (/Users/u/dev/atlaskit-mk-2/node_modules/simple-git/src/git.js:1482:18)
    at mergeHandler (/Users/u/dev/atlaskit-mk-2/node_modules/simple-git/src/git.js:868:24)
    at Git.<anonymous> (/Users/u/dev/atlaskit-mk-2/node_modules/simple-git/src/git.js:1564:10)
    at done (/Users/u/dev/atlaskit-mk-2/node_modules/simple-git/src/git.js:1436:21)
    at /Users/u/dev/atlaskit-mk-2/node_modules/simple-git/src/git.js:1461:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by steveukx** [comment]
Thank you for pointing this out.

The first line of the error stack trace contains the `toString` value of a MergeSummary when it has conflicts, which could be parsed but isn't that useful... 

As of 1.129.0 (available on npm now), the promise based api will include the parsed response as a property on the caught exception - an example is also now in the readme at https://github.com/steveukx/git-js#promise-and-async-compatible

**Comment by Blasz** [comment]
Great, thanks for that @steveukx!
