### ISSUE TITLE
TypeError: simple_git_1.default is not a function

### ISSUE THREAD

**Issue by williamdes** [steveukx/git-js#473]
I am migrating to typescript and I have the following error:
```
$ ./bin/sudo-bot.js --env ./
/mnt/Dev/@sudo/sudo-bot/dist/files.js:71
    const sg = simple_git_1.default(process.env.REPO_DIR);
                                   ^

TypeError: simple_git_1.default is not a function
    at Object.listGitModifiedFiles (/mnt/Dev/@sudo/sudo-bot/dist/files.js:71:36)
    at Object.doProcess [as default] (/mnt/Dev/@sudo/sudo-bot/dist/index.js:21:21)
    at Object.<anonymous> (/mnt/Dev/@sudo/sudo-bot/bin/sudo-bot.js:16:46)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

Ref: https://github.com/sudo-bot/sudo-bot/pull/76

Before the migration it worked well

## Dist
```js
const simple_git_1 = require("simple-git");
const listGitModifiedFiles = function (cbSuccess) {
    const sg = simple_git_1.default(process.env.REPO_DIR);
    sg.status().then((status) => {
        cbSuccess(status.modified);
    });
};
```

## TS
```ts
import simpleGit, {SimpleGit} from 'simple-git';
const listGitModifiedFiles = function (cbSuccess: (status: any) => void) {
    const sg: SimpleGit = simpleGit(process.env.REPO_DIR);
    sg.status().then((status) => {
        cbSuccess(status.modified);
    });
};
```

I do not understand what is wrong to make TS use .default

**Comment by steveukx** [comment]
Hi, thank you for opening the issue.

Up until now, it has been necessary to use the `esModuleInterop` option in your `tsconfig.json` to add the `.default`. Version 2.8.0, available on npm now, works natively as an es module so you should find this is now resolved. If you do have any other problems, please re-open this issue.
