### ISSUE TITLE
Unable to get rev-parse --short to work

### ISSUE THREAD

**Issue by unphased** [steveukx/git-js#491]
This is what I tried in the node REPL: 

```
> git().revparse('HEAD', {"--short":null}).then(e => console.log(e))
Promise { <pending> }
> (node:56900) UnhandledPromiseRejectionWarning: Error: fatal: Needed a single revision

    at GitExecutorChain.onFatalException (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)
    at GitExecutorChain.<anonymous> (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)
    at Generator.throw (<anonymous>)
    at rejected (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:56900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:56900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> git().raw(['rev-parse', 'HEAD', '--short']).then(e => console.log(e))
Promise { <pending> }
> (node:56900) UnhandledPromiseRejectionWarning: Error: fatal: Needed a single revision

    at GitExecutorChain.onFatalException (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)
    at GitExecutorChain.<anonymous> (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)
    at Generator.throw (<anonymous>)
    at rejected (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:56900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

(To exit, press ^C again or ^D or type .exit)
> git().revparse(['HEAD', {"--short":null}]).then(e => console.log(e))
Promise { <pending> }
> 94161e4185a1e5c3a9ee49b580ef27df1e622122
[object Object]
> git().revparse(['HEAD', "--short"]).then(e => console.log(e))
Promise { <pending> }
> (node:56900) UnhandledPromiseRejectionWarning: Error: fatal: Needed a single revision

    at GitExecutorChain.onFatalException (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)
    at GitExecutorChain.<anonymous> (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)
    at Generator.throw (<anonymous>)
    at rejected (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:56900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
> git().revparse('HEAD', ["--short"]).then(e => console.log(e))
Promise { <pending> }
> \(node:56900) UnhandledPromiseRejectionWarning: Error: fatal: Needed a single revision

    at GitExecutorChain.onFatalException (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)
    at GitExecutorChain.<anonymous> (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)
    at Generator.throw (<anonymous>)
    at rejected (/Users/slu/Documents/integration-testing/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:56900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)

>
```

As you can see, I was able to avoid the exception with `git().revparse(['HEAD', {"--short":null}])`, however, this still fails to actually use the `short` flag I'm trying to send. 

Could someone provide guidance for the `fatal: Needed a single revision` error?

**Comment by steveukx** [comment]
The problem is to do with the ordering of your commands try:

```typescript
git().revparse(['--short', 'HEAD']);
```

to ensure the git command being run is `git rev-parse --short HEAD` rather than `git rev-parse HEAD --short`

**Comment by unphased** [comment]
Ah, crap, what a dumb oversight. Thank you. 

```
> git().revparse(['--short','HEAD']).then(e=>console.log(e))
Promise { <pending> }
> 6fdef48
```

cheers!
