### ISSUE TITLE
git-error when commit on Github Action

### ISSUE THREAD

**Issue by jiyeonseo** [steveukx/git-js#513]
tried to git clone, change, push works using github action. 

it's totally working well on my local but there is TypeError when I try to `.commit("msg")` on Github Action. 
the error is like below : 

```
TypeError: Object prototype may only be an Object or null: undefined
    at Function.setPrototypeOf (<anonymous>)
    at new GitError (/myproject/webpack:/javascript-action/node_modules/simple-git/src/lib/errors/git-error.js:32:1)
    at GitExecutorChain.onFatalException (/myproject/webpack:/javascript-action/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:1)
    at GitExecutorChain.<anonymous> (/myproject/webpack:/javascript-action/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:1)
    at Generator.throw (<anonymous>)
    at rejected (/myproject/webpack:/javascript-action/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
my code is like: 
```node
await git(__dirname + "/tmp")
        .commit("msg") 
        .catch((err) => {console.log(err)})
```
Github action is like : (it happens on every node versions) 
```
jobs:
  myproject:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         node-version: [10.x, 12.x, 14.x]
```

clone, add, push are totally fine. 
If I'm doing something wrong, please let me know.

**Comment by steveukx** [comment]
Hi

In order to look into this for you, please can you share more of the code you are using to interact with `simple-git` in the action, and also how you are bundling your action (through what appears to be webpack).

If you could also include the use of `simple-git` that works (ie: the initial git clone) that would give me a good starting point to create a test for you.

You can enable debug logs by setting the `DEBUG` environment variable to `*` or `simple-git,simple-git:*,@kwsites/file-exists` which will log all commands generated by the library and any validation of the repo being found in the file system.
