### ISSUE TITLE
git apply

### ISSUE THREAD

**Issue by andreterron** [steveukx/git-js#540]
Thanks for this library!

[git apply](https://git-scm.com/docs/git-apply) is missing from the available commands, and I was interested in using it.

Let me know if I can help somehow.

I tried to fork it and raise a PR, but the tests weren't passing on my machine with the following issue (same issue for all the failing tests):

```
 FAIL  test/unit/config.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    <path>/test/unit/__mocks__/mock-child-process.ts:21
      $handlers = new Map();
                ^

    SyntaxError: Unexpected token =

    > 1 | import { MockChildProcess, mockChildProcessModule } from '../__mocks__/mock-child-process';
        | ^
      2 | import { wait } from '../../__fixtures__';
      3 |
      4 | const EXIT_CODE_SUCCESS = 0;

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (test/unit/__fixtures__/child-processes.ts:1:1)


Test Suites: 50 failed, 15 passed, 65 total
Tests:       25 failed, 75 passed, 100 total
Snapshots:   0 total
Time:        8.717 s, estimated 12 s
Ran all test suites.
```

**Comment by steveukx** [comment]
Hi, thanks for taking the time to try the tests :) to set up the development environment you should need nothing more than git, node.js 12+ or above and a global install of yarn (classic)

```
> git --version
git version 2.24.3 (Apple Git-128)

> node -v
v12.16.2

> yarn -v
1.22.4

> cd git-js
> yarn && yarn clean && yarn test
```

The final step will `yarn` install all dependencies, `yarn clean` remove any of the generated JavaScript / maps etc and `yarn test` to run the consumer / integration and unit tests.

It's worth noting that as most of the tests are written in TypeScript, you will need to be running through jest as configured in the `jest.config.js` in the project to ensure they're transpiled on the fly.

If you would like to go ahead with a pull request, please do - you'll see the emerging pattern of making a few separate files:

- ./src/lib/tasks/apply-patch.ts
- ./src/lib/parsers/parse-apply-patch.ts (if you're planning to parse the response)
- ./test/unit/apply-patch.spec.ts (unit test coverage, particularly useful if you make a parser)

And modifying:
./src/git.js - add a new method such as `Git.prototype.applyPatch`
./typings/simple-git.d.ts - add your new method and the associated type definition

If you would prefer to just run your commands through `simple-git` without modifying the library, you can use `git.raw` as documented in [complex requests](https://github.com/steveukx/git-js#complex-requests):

```
const repo = './path/to/repo';
const patch = './path/to/diff.patch';
const git = simpleGit(repo);

console.log(await git.raw('apply', patch))
```

**Comment by andreterron** [comment]
It was indeed my node version, great catch!

PR created!

**Comment by steveukx** [comment]
Hi, thank you for the great pull request. I've merged your code along as part of the squash commit for version 2.28.0 so the PR was manually rather than automatically closed.

You can now make use of the git.applyPatch method in version 2.28.0 on npm now.
