### ISSUE TITLE
Issue with Git-core 2.30.1

### ISSUE THREAD

**Issue by dma82** [steveukx/git-js#588]
Hi there,

We recently ungraded Git from 2.24.1 to 2.30.1 (which has been released a couple of weeks ago) on our Linux server, and as a result this module stopped working (please see the below log), so eventually we had to revert the upgrade to its previous version.

I'm not sure if if they changed something in the git-diff (https://centos.pkgs.org/7/endpoint-x86_64/git-2.30.1-1.ep7.x86_64.rpm.html ). Would you be able to have a look at this if you have a chance please?

Thanks very much.

```
usage: git diff [<options>] [<commit>] [--] [<path>...]
   or: git diff [<options>] --cached [<commit>] [--] [<path>...]
   or: git diff [<options>] <commit> [--merge-base] [<commit>...] <commit> [--] [<path>...]
   or: git diff [<options>] <commit>...<commit>] [--] [<path>...]
   or: git diff [<options>] <blob> <blob>]
   or: git diff [<options>] --no-index [--] <path> <path>]
common diff options:
  -z            output diff-raw with lines terminated with NUL.
  -p            output patch format.
  -u            synonym for -p.
  --patch-with-raw
                output both a patch and the diff-raw format.
  --stat        show diffstat instead of patch.
  --numstat     show numeric diffstat instead of patch.
  --patch-with-stat
                output a patch and prepend its diffstat.
  --name-only   show only names of changed files.
  --name-status show names and status of changed files.
  --full-index  show full object name on index lines.
  --abbrev=<n>  abbreviate object names in diff-tree header and diff-raw.
  -R            swap input file pairs.
  -B            detect complete rewrites.
  -M            detect renames.
  -C            detect copies.
  --find-copies-harder
                try unchanged files as candidate for copy detection.
  -l<n>         limit rename attempts up to <n> paths.
  -O<file>      reorder diffs according to the <file>.
  -S<string>    find filepair whose only one side contains the string.
  --pickaxe-all
                show all files diff when -S is used and hit is found.
  -a  --text    treat all files as text.
Error Error: usage: git diff [<options>] [<commit>] [--] [<path>...]
   or: git diff [<options>] --cached [<commit>] [--] [<path>...]
   or: git diff [<options>] <commit> [--merge-base] [<commit>...] <commit> [--] [<path>...]
   or: git diff [<options>] <commit>...<commit>] [--] [<path>...]
   or: git diff [<options>] <blob> <blob>]
   or: git diff [<options>] --no-index [--] <path> <path>]
common diff options:
  -z            output diff-raw with lines terminated with NUL.
  -p            output patch format.
  -u            synonym for -p.
  --patch-with-raw
                output both a patch and the diff-raw format.
  --stat        show diffstat instead of patch.
  --numstat     show numeric diffstat instead of patch.
  --patch-with-stat
                output a patch and prepend its diffstat.
  --name-only   show only names of changed files.
  --name-status show names and status of changed files.
  --full-index  show full object name on index lines.
  --abbrev=<n>  abbreviate object names in diff-tree header and diff-raw.
  -R            swap input file pairs.
  -B            detect complete rewrites.
  -M            detect renames.
  -C            detect copies.
  --find-copies-harder
                try unchanged files as candidate for copy detection.
  -l<n>         limit rename attempts up to <n> paths.
  -O<file>      reorder diffs according to the <file>.
  -S<string>    find filepair whose only one side contains the string.
  --pickaxe-all
                show all files diff when -S is used and hit is found.
  -a  --text    treat all files as text.
    at /home/git-user/test1/tool/node_modules/simple-git/promise.js:21:26
    at /home/git-user/test1/tool/node_modules/simple-git/src/git.js:1510:13
    at Git.<anonymous> (/home/git-user/test1/tool/node_modules/simple-git/src/git.js:1053:18)
    at Function.Git.fail (/home/git-user/test1/tool/node_modules/simple-git/src/git.js:1435:18)
    at fail (/home/git-user/tool/test1/node_modules/simple-git/src/git.js:1393:20)
    at /home/git-user/tool/test1/node_modules/simple-git/src/git.js:1402:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error generating release script
```

**Comment by steveukx** [comment]
Hi, in order to look into this for you, please can you include the node script - specifically how you're require/importing `simple-git` and how you call the `git.diff(...)`.

It looks as though you are importing `simple-git/promise` which was deprecated from v2.6.0 - while everything should still work as expected I would recommend trying with the main `simple-git` import.

If you are able to run with [debugging output enabled](https://github.com/steveukx/git-js#enable-verbose-logging) (set an environment variable `DEBUG=simple-git:task:diff:*` or for all logging use `DEBUG=simple-git,simple-git*`), please also send the output around the use of git.diff.

Thanks

**Comment by dma82** [comment]
Hi Steve, thank you for coming back to me. You are actually right: I do import `simple-git/promise` and still using v1.92.0. I will upgrade it to the current version and change that import and I will let you know.
Thank you again for your help with this.
Regards,
