### ISSUE TITLE
[Feature Request] Merge strategies

### ISSUE THREAD

**Issue by KnisterPeter** [steveukx/git-js#607]
Hi,

there current `merge` and `mergeFromTo` functions do not seem to support advanced merge options.
It would be nice to add merge strategies.

```
  simple-git [GitExecutor] [HANDLE] retrieving task output complete +0ms
  simple-git [GitExecutor] [SPAWN] git [ 'merge', 'origin/71aBz-some-changes-team-a', '71aBz-some-changes', '--no-edit', '-s=recursive', '-X=theirs' ] +4ms
  simple-git [GitExecutor] [SPAWN] exitCode=0 event=close rejection=undefined +14ms
  simple-git [GitExecutor] [SPAWN] exitCode=0 event=deferred rejection=undefined +0ms
  simple-git [GitExecutor] [SPAWN] exitCode=1 event=exit rejection=undefined +7ms
  simple-git [GitExecutor] [HANDLE] handling as error: exitCode=1 stdErr=1 rejection=undefined +0ms
  simple-git [GitExecutor]  Failed GitError: Could not find merge strategy '=recursive'. Available strategies are: octopus ours recursive resolve subtree.  at GitExecutorChain.onFatalException (/home/markusw/source/rezensent/.yarn/cache/simple-git-npm-2.36.2-b4e0bb6f78-59bd368e8a.zip/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:76:77) at GitExecutorChain.<anonymous> (/home/markusw/source/rezensent/.yarn/cache/simple-git-npm-2.36.2-b4e0bb6f78-59bd368e8a.zip/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:68:21) at Generator.throw (<anonymous>) at rejected (/home/markusw/source/rezensent/.yarn/cache/simple-git-npm-2.36.2-b4e0bb6f78-59bd368e8a.zip/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65) at runMicrotasks (<anonymous>)     at processTicksAndRejections (internal/process/task_queues.js:93:5) { task: { commands: [ 'merge', 'origin/71aBz-some-changes-team-a', '71aBz-some-changes', '--no-edit', '-s=recursive', '-X=theirs' ], format: 'utf-8', parser: [Function: parser] } } +2ms
  simple-git [GitExecutor] [SPAWN] exitCode=1 event=close rejection=undefined +41ms
  simple-git [GitExecutor] [SPAWN] exitCode=0 event=deferred rejection=undefined +0ms
ERROR (event): Could not find merge strategy '=recursive'.
Available strategies are: octopus ours recursive resolve subtree.

    Error: Could not find merge strategy '=recursive'.
    Available strategies are: octopus ours recursive resolve subtree.
    
        at GitExecutorChain.onFatalException (/home/markusw/source/rezensent/.yarn/cache/simple-git-npm-2.36.2-b4e0bb6f78-59bd368e8a.zip/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:76:77)
        at GitExecutorChain.<anonymous> (/home/markusw/source/rezensent/.yarn/cache/simple-git-npm-2.36.2-b4e0bb6f78-59bd368e8a.zip/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:68:21)
        at Generator.throw (<anonymous>)
        at rejected (/home/markusw/source/rezensent/.yarn/cache/simple-git-npm-2.36.2-b4e0bb6f78-59bd368e8a.zip/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by KnisterPeter** [comment]
The error seem to be on my side.
