### ISSUE TITLE
No MergeSummary if a binary file has a conflict

### ISSUE THREAD

**Issue by taras-dubyk** [steveukx/git-js#838]
Merge works fine in case of conflicts between text files. It throws MergeSummary with parsed conflicts.
But when there is a conflict between binary files, merge throws an error without MergeSummary.

I suppose it should work the same for both cases, as the git response is pretty the same and just includes one additional line in case of binary file conflict: `warning: Cannot merge binary files: 1.png (HEAD vs. myBranch)`

`simpleGit.merge(['myBranch']);`
Stack trace:

>  'Error: Auto-merging 1.png
> CONFLICT (content): Merge conflict in 1.png
> Automatic merge failed; fix conflicts and then commit the result.
> warning: Cannot merge binary files: 1.png (HEAD vs. myBranch)
> 
>     at Object.action (/home/taras/Dev/git-test/node_modules/simple-git/dist/cjs/index.js:1194:25)
>     at PluginStore.exec (/home/taras/Dev/git-test/node_modules/simple-git/dist/cjs/index.js:1229:29)
>     at /home/taras/Dev/git-test/node_modules/simple-git/dist/cjs/index.js:1590:43
>     at new Promise (<anonymous>)
>     at GitExecutorChain.handleTaskData (/home/taras/Dev/git-test/node_modules/simple-git/dist/cjs/index.js:1588:16)
>     at GitExecutorChain.<anonymous> (/home/taras/Dev/git-test/node_modules/simple-git/dist/cjs/index.js:1572:44)
>     at Generator.next (<anonymous>)
>     at fulfilled (/home/taras/Dev/git-test/node_modules/simple-git/dist/cjs/index.js:55:24)'

**Comment by begin-again** [comment]
I'm seeing this too on v3.20.0

**Comment by begin-again** [comment]
This expected behavior, I just needed to read deeper than the README

https://github.com/steveukx/git-js/blob/8a31c45a1359248cb38d768d22a5e29903ceef8a/simple-git/src/lib/errors/git-response-error.ts#L5
