### ISSUE TITLE
`TypeError: arg.trim is not a function`

### ISSUE THREAD

**Issue by Ndpnt** [steveukx/git-js#866]
Hi,

Since the version `3.15.0` we get the following error:

```sh
Error: TypeError: arg.trim is not a function
    at GitExecutorChain.onFatalException (file:///Users/ndpnt/.nvm/versions/node/v16.15.1/lib/node_modules/@opentermsarchive/engine/node_modules/simple-git/dist/esm/index.js:1220:79)
    at GitExecutorChain.<anonymous> (file:///Users/ndpnt/.nvm/versions/node/v16.15.1/lib/node_modules/@opentermsarchive/engine/node_modules/simple-git/dist/esm/index.js:1212:24)
    at Generator.throw (<anonymous>)
    at rejected (file:///Users/ndpnt/.nvm/versions/node/v16.15.1/lib/node_modules/@opentermsarchive/engine/node_modules/simple-git/dist/esm/index.js:57:29)
```

Here is our initialization code:
```js
    …
    this.git = simpleGit(this.path, { maxConcurrentProcesses: 1 });

    await this.git.init();

    return this.git
      .addConfig('core.autocrlf', false)
      .addConfig('push.default', 'current')
      .addConfig('user.name', this.author.name)
      .addConfig('user.email', this.author.email);
```

We can fix the issue by adding `{ unsafe: { allowUnsafeProtocolOverride: true } }`:
```js
    …
    this.git = simpleGit(this.path, { maxConcurrentProcesses: 1, unsafe: { allowUnsafeProtocolOverride: true } });

    await this.git.init();

    return this.git
      .addConfig('core.autocrlf', false)
      .addConfig('push.default', 'current')
      .addConfig('user.name', this.author.name)
      .addConfig('user.email', this.author.email);
```

But I wondered if this was the right way to fix the issue?

_Note: Thus, unless I am mistaken, the minor release `3.15.0` seems to add a breaking change._

**Comment by steveukx** [comment]
Hello, thanks for the detailed stack trace.

I've created a patch `3.15.1` which is available on npm now that should resolve this error. Please let me know if you continue to see the error.

**Comment by Ndpnt** [comment]
Everything is working fine now. Thank you very much for your responsiveness!
