### ISSUE TITLE
Will not accept my git username and email

### ISSUE THREAD

**Issue by Daxcor69** [steveukx/git-js#878]
I had this working about a month ago.  I went back to do a final run through before releasing and discoverd an issue where simple-git doesn't recognize my user info.  I am using simple-git": "^3.15.1",  on nodejs 18

Here is my code

```
     // we need to extract the version from the url.
     // sample url  https://found.s3.amazonaws.com/releases/10.286/Found-10.286.zip?AWSAccessKeyId=AKIA2KC
      const mysplit = req.body.url.split("/");
      const version = mysplit[4];
      const gitRemote = "https://server:glpat-blahblah@gitlab.com/server/source";

      //set up git config.
      const { simpleGit } = require("simple-git");
      simpleGit().clean(simpleGit.CleanOptions.FORCE);

      simpleGit().addConfig("user.name", "Admin Pod").addConfig("user.email", "admin@server.com");

      await simpleGit().clone(gitRemote, "/tmp/source");
      const git = simpleGit("/tmp/source");

      // edit url.txt with new url for download.
      fs.writeFileSync("/tmp/source/url.txt", req.body.url);

      // lets add the new version to the local git and then push.
      response = await git.add(".");
      response = await git.commit(version);
      response = await git.push();
```

Here is the error I am getting.
```
error GitError: Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'nodeuser@admin-server-588448f79b-hnvqq.(none)')

    at Object.action (/home/nodeuser/node_modules/simple-git/dist/cjs/index.js:1261:25)
    at PluginStore.exec (/home/nodeuser/node_modules/simple-git/dist/cjs/index.js:1296:29)
    at /home/nodeuser/node_modules/simple-git/dist/cjs/index.js:1661:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/home/nodeuser/node_modules/simple-git/dist/cjs/index.js:1659:16)
    at GitExecutorChain.<anonymous> (/home/nodeuser/node_modules/simple-git/dist/cjs/index.js:1643:44)
    at Generator.next (<anonymous>)
    at fulfilled (/home/nodeuser/node_modules/simple-git/dist/cjs/index.js:55:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  task: {
    commands: [ '-c', 'core.abbrev=40', 'commit', '-m', '10.288' ],
    format: 'utf-8',
    parser: [Function: parseCommitResult]
  }
}
```

**Comment by Rub21** [comment]
@Daxcor69  Add  user.name and user.email using `await` and check.

```sh
  await git.addConfig("user.name", "argos")
  await git.addConfig("user.email", "argos@g.com")
  await git.listConfig()
```
