### ISSUE TITLE
Git clone fails with error: `unable to write file .../.git/objects/pack/pack-21e4d1ed8f4db69e78405187f3c4c4dd177b46c5.pack: No such file or directory`

### ISSUE THREAD

**Issue by seunggs** [steveukx/git-js#911]
Using simple-git, git clone fails (but only for some repos) with the following error:

```
remote: Enumerating objects: 5844, done.        
remote: Counting objects: 100% (3/3), done.          
remote: Compressing objects: 100% (3/3), done.          
remote: Total 5844 (delta 0), reused 0 (delta 0), pack-reused 5841        
Receiving objects: 100% (5844/5844), 1.20 GiB | 16.78 MiB/s, done./s
error: unable to write file /userRepoData/taeefnajib/COVID-19-Pneumonia-Classification-Using-EfficientNet/.git/objects/pack/pack-21e4d1ed8f4db69e78405187f3c4c4dd177b46c5.pack: No such file or directory
fatal: cannot store pack file
fatal: index-pack failed

    at Object.action (/root/node_modules/simple-git/dist/cjs/index.js:1274:25)
    at PluginStore.exec (/root/node_modules/simple-git/dist/cjs/index.js:1309:29)
    at /root/node_modules/simple-git/dist/cjs/index.js:1676:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/root/node_modules/simple-git/dist/cjs/index.js:1674:16)
    at GitExecutorChain.<anonymous> (/root/node_modules/simple-git/dist/cjs/index.js:1658:44)
    at Generator.next (<anonymous>)
    at fulfilled (/root/node_modules/simple-git/dist/cjs/index.js:55:24) {
  task: {
    commands: [
      'clone',
      'https://taeefnajib:REDACTED@github.com/taeefnajib/COVID-19-Pneumonia-Classification-Using-EfficientNet.git'
    ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}
```

It's important to note that this only occurs on an express server running inside a remote linux container (a Kubernetes pod running in aws eks). I can, however, run git clone fine if I `exec -it` into the container and run the command manually in the terminal.

I couldn't fine a solution anywhere, so thanks in advance for looking into this!

**Comment by steveukx** [comment]
Hi, a couple of questions around your use case... do you:

- always clone the same repo and sometimes it fails
- clone from a variety of repos and this one fails sometimes
- clone from a variety of repos, this is just an example of one that fails

The repo in your example is fairly large (downloads at over 1Gb), is it possible your pod runs out of storage?

Do you clean up cloned repos once they've been used?
