### ISSUE TITLE
Error on windows when on different drive

### ISSUE THREAD

**Issue by josh-hemphill** [steveukx/git-js#962]
`GitError: fatal: invalid object name 'E'`
<details>
  <summary>Full error</summary>
  

```
at Object.action (E:\Share\dev\vueuse\node_modules\.pnpm\simple-git@3.21.0\node_modules\simple-git\src\lib\plugins\error-detection.plugin.ts:42:29)
    at PluginStore.exec (E:\Share\dev\vueuse\node_modules\.pnpm\simple-git@3.21.0\node_modules\simple-git\src\lib\plugins\plugin-store.ts:29:29)
    at <anonymous> (E:\Share\dev\vueuse\node_modules\.pnpm\simple-git@3.21.0\node_modules\simple-git\src\lib\runners\git-executor-chain.ts:127:42)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (E:\Share\dev\vueuse\node_modules\.pnpm\simple-git@3.21.0\node_modules\simple-git\src\lib\runners\git-executor-chain.ts:124:14)
    at GitExecutorChain.<anonymous> (E:\Share\dev\vueuse\node_modules\.pnpm\simple-git@3.21.0\node_modules\simple-git\src\lib\runners\git-executor-chain.ts:100:40)
    at Generator.next (<anonymous>)
    at fulfilled (file:///E:/Share/dev/vueuse/node_modules/.pnpm/simple-git@3.21.0/node_modules/simple-git/dist/esm/index.js:50:24) {
  task: {
    commands: [
      'log',
      '-1',
      '--format=%at',
      'E:\\Share\\dev\\vueuse\\packages\\shared\\resolveRef\\index.ts'
    ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}
```
  
</details>

Looks like it's a string escaping issue, it's separating at the colon. I've tried adding quotes where it gets passed in, and that doesn't seem to help at all (I assume it's already feeding it to the shell as string) but parsing the colon seems to happen elsewhere to create the issue.

I found where VueUse is calling this it's just `await git.raw(['log', '-1', '--format=%at', tsPath]) * 1000` apparently using that to get the lastUpdated of the files, but I'm not sure what to do to get it to work with windows drive paths.

**Comment by steveukx** [comment]
Hi, you can add a path spec separator to the command, either explicitly:

```typescript
await git.raw(['log', '-1', '--format=%at', '--', tsPath])
```

or with the helper (see [docs]https://github.com/steveukx/git-js#using-a-pathspec-to-limit-the-scope-of-the-task)):

```typescript
import { simpleGit, pathspec } from "simple-git";

await git.raw(['log', '-1', '--format=%at', pathspec(tsPath)])
```

If those don't work, please run with [full verbose debugging enabled](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md#verbose-logging-options) and add to this issue the complete section around the `git log` child process.
