### ISSUE TITLE
replace "node:events" with  'events'

### ISSUE THREAD

**Issue by sirgalahadcm** [steveukx/git-js#997]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `simple-git@3.24.0` for the project I'm working on.

```javasript
 ENOENT: no such file or directory, open 'node:events'

    > 1 | const simpleGit = require('simple-git');
        |                   ^
      2 | const fs = require('fs');
      3 | const path = require('path');
      4 |

      at Runtime.readFile (node_modules/jest-runtime/build/index.js:1987:21)
      at src/lib/plugins/plugin-store.ts (node_modules/simple-git/src/lib/plugins/plugin-store.ts:1:30)
      at __init (node_modules/simple-git/dist/cjs/index.js:26:56)
      at src/lib/plugins/index.ts (node_modules/simple-git/src/lib/plugins/index.ts:7:1)
      at __init (node_modules/simple-git/dist/cjs/index.js:26:56)
      at src/lib/git-factory.ts (node_modules/simple-git/src/lib/git-factory.ts:4:1)
      at __init (node_modules/simple-git/dist/cjs/index.js:26:56)
      at src/lib/runners/promise-wrapped.ts (node_modules/simple-git/src/lib/runners/promise-wrapped.ts:4:1)
      at __init (node_modules/simple-git/dist/cjs/index.js:26:56)
      at Object.<anonymous> (node_modules/simple-git/src/index.js:1:18)
      at Object.<anonymous> (src/migrations.test.js:1:19)
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/simple-git/dist/cjs/index.js b/node_modules/simple-git/dist/cjs/index.js
index 8b569aa..6ff5956 100644
--- a/node_modules/simple-git/dist/cjs/index.js
+++ b/node_modules/simple-git/dist/cjs/index.js
@@ -1462,7 +1462,7 @@ var import_node_events, PluginStore;
 var init_plugin_store = __esm({
   "src/lib/plugins/plugin-store.ts"() {
     "use strict";
-    import_node_events = require("node:events");
+    import_node_events = require('events');
     init_utils();
     PluginStore = class {
       constructor() {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by steveukx** [comment]
Hello, which version of node.js are you using? `simple-git` is tested against node 18, 20 and 21.

**Comment by sirgalahadcm** [comment]
I am trying to switch from 18 to 20 and this issue came up, but I think now it might be a config issue on my end. All uses of node:something are failing

**Comment by steveukx** [comment]
I'll close this for now then... if you have any further problems though please create a new issue.
🤞 for the rest of the upgrade!
